package httpx

import (
	"bytes"
	"encoding/json"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
)

func TestRequestIDMiddleware(t *testing.T) {
	gin.SetMode(gin.TestMode)

	router := gin.New()
	router.Use(RequestIDMiddleware())

	router.GET("/test", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"request_id": RequestID(c),
		})
	})

	requestIDs := make([]string, 0, 2)

	for i := 0; i < 2; i++ {
		request := httptest.NewRequest(http.MethodGet, "/test", nil)
		request.Header.Set(HeaderRequestID, "client-supplied-id")

		recorder := httptest.NewRecorder()
		router.ServeHTTP(recorder, request)

		if recorder.Code != http.StatusOK {
			t.Fatalf("expected status %d, got %d", http.StatusOK, recorder.Code)
		}

		responseID := recorder.Header().Get(HeaderRequestID)
		if responseID == "" {
			t.Fatal("expected response to contain a request ID")
		}

		if responseID == "client-supplied-id" {
			t.Fatal("request ID must be generated by the server")
		}

		var body struct {
			RequestID string `json:"request_id"`
		}

		if err := json.Unmarshal(recorder.Body.Bytes(), &body); err != nil {
			t.Fatalf("decode response body: %v", err)
		}

		if body.RequestID != responseID {
			t.Fatalf(
				"expected context request ID %q to match response header %q",
				body.RequestID,
				responseID,
			)
		}

		requestIDs = append(requestIDs, responseID)
	}

	if requestIDs[0] == requestIDs[1] {
		t.Fatal("expected different requests to receive different request IDs")
	}
}

func TestRecoveryMiddleware(t *testing.T) {
	gin.SetMode(gin.TestMode)

	logger, logs := newTestLogger()

	router := gin.New()
	router.Use(
		RequestIDMiddleware(),
		RecoveryMiddleware(logger),
		AccessLogMiddleware(logger),
	)

	const panicMessage = "PANIC_SECRET_DO_NOT_LEAK"

	router.GET("/panic", func(_ *gin.Context) {
		panic(panicMessage)
	})

	request := httptest.NewRequest(http.MethodGet, "/panic", nil)
	recorder := httptest.NewRecorder()

	router.ServeHTTP(recorder, request)

	if recorder.Code != http.StatusInternalServerError {
		t.Fatalf(
			"expected status %d, got %d",
			http.StatusInternalServerError,
			recorder.Code,
		)
	}

	contentType := recorder.Header().Get("Content-Type")
	if !strings.HasPrefix(contentType, "application/json") {
		t.Fatalf("expected JSON content type, got %q", contentType)
	}

	var response ErrorResponse
	if err := json.Unmarshal(recorder.Body.Bytes(), &response); err != nil {
		t.Fatalf("decode recovery response: %v", err)
	}

	if response.Code != CodeInternalError {
		t.Fatalf("expected error code %q, got %q", CodeInternalError, response.Code)
	}

	if response.Message != "internal server error" {
		t.Fatalf("unexpected client message %q", response.Message)
	}

	responseID := recorder.Header().Get(HeaderRequestID)
	if responseID == "" {
		t.Fatal("expected response to contain a request ID")
	}

	if response.RequestID != responseID {
		t.Fatalf(
			"expected body request ID %q to match header %q",
			response.RequestID,
			responseID,
		)
	}

	responseBody := recorder.Body.String()
	if strings.Contains(responseBody, panicMessage) {
		t.Fatal("recovery response leaked the panic message")
	}

	if strings.Contains(responseBody, "goroutine") {
		t.Fatal("recovery response leaked a stack trace")
	}

	records := decodeLogRecords(t, logs.Bytes())

	recoveryLog := findLogRecord(t, records, "panic recovered")
	if recoveryLog.Level != "ERROR" {
		t.Fatalf("expected recovery log level ERROR, got %q", recoveryLog.Level)
	}

	if recoveryLog.Module != "http" {
		t.Fatalf("expected recovery log module http, got %q", recoveryLog.Module)
	}

	if recoveryLog.RequestID != responseID {
		t.Fatalf(
			"expected recovery log request ID %q, got %q",
			responseID,
			recoveryLog.RequestID,
		)
	}

	if recoveryLog.Method != http.MethodGet {
		t.Fatalf("expected recovery log method GET, got %q", recoveryLog.Method)
	}

	if recoveryLog.Path != "/panic" {
		t.Fatalf("expected recovery log path /panic, got %q", recoveryLog.Path)
	}

	if recoveryLog.Error != panicMessage {
		t.Fatalf("expected recovery log to contain the panic value")
	}

	if recoveryLog.Stack == "" {
		t.Fatal("expected recovery log to contain a server-side stack trace")
	}

	accessLog := findLogRecord(t, records, "http request completed")
	assertAccessLog(
		t,
		accessLog,
		responseID,
		http.MethodGet,
		"/panic",
		http.StatusInternalServerError,
	)
}

func TestAccessLogMiddleware(t *testing.T) {
	gin.SetMode(gin.TestMode)

	logger, logs := newTestLogger()

	router := gin.New()
	router.Use(
		RequestIDMiddleware(),
		RecoveryMiddleware(logger),
		AccessLogMiddleware(logger),
	)

	router.POST("/audit", func(c *gin.Context) {
		c.JSON(http.StatusCreated, gin.H{
			"request_id": RequestID(c),
		})
	})

	request := httptest.NewRequest(
		http.MethodPost,
		"/audit?password=QUERY_SECRET",
		strings.NewReader(`{"password":"BODY_SECRET"}`),
	)
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Authorization", "Bearer AUTH_SECRET")

	recorder := httptest.NewRecorder()
	router.ServeHTTP(recorder, request)

	if recorder.Code != http.StatusCreated {
		t.Fatalf(
			"expected status %d, got %d",
			http.StatusCreated,
			recorder.Code,
		)
	}

	responseID := recorder.Header().Get(HeaderRequestID)
	if responseID == "" {
		t.Fatal("expected response to contain a request ID")
	}

	var response struct {
		RequestID string `json:"request_id"`
	}
	if err := json.Unmarshal(recorder.Body.Bytes(), &response); err != nil {
		t.Fatalf("decode response: %v", err)
	}

	if response.RequestID != responseID {
		t.Fatalf(
			"expected handler request ID %q to match header %q",
			response.RequestID,
			responseID,
		)
	}

	records := decodeLogRecords(t, logs.Bytes())
	accessLog := findLogRecord(t, records, "http request completed")
	assertAccessLog(
		t,
		accessLog,
		responseID,
		http.MethodPost,
		"/audit",
		http.StatusCreated,
	)

	logOutput := logs.String()
	for _, secret := range []string{
		"QUERY_SECRET",
		"BODY_SECRET",
		"AUTH_SECRET",
	} {
		if strings.Contains(logOutput, secret) {
			t.Fatalf("access log leaked sensitive value %q", secret)
		}
	}

	if strings.Contains(strings.ToLower(logOutput), "authorization") {
		t.Fatal("access log must not record the Authorization header")
	}
}

type testLogRecord struct {
	Level      string `json:"level"`
	Message    string `json:"msg"`
	Module     string `json:"module"`
	RequestID  string `json:"request_id"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Status     int    `json:"status"`
	DurationMS *int64 `json:"duration_ms"`
	Error      string `json:"error"`
	Stack      string `json:"stack"`
}

func newTestLogger() (*slog.Logger, *bytes.Buffer) {
	var output bytes.Buffer
	handler := slog.NewJSONHandler(&output, nil)

	return slog.New(handler), &output
}

func decodeLogRecords(t *testing.T, data []byte) []testLogRecord {
	t.Helper()

	decoder := json.NewDecoder(bytes.NewReader(data))
	records := make([]testLogRecord, 0)

	for {
		var record testLogRecord

		err := decoder.Decode(&record)
		if err == io.EOF {
			return records
		}
		if err != nil {
			t.Fatalf("decode log record: %v", err)
		}

		records = append(records, record)
	}
}

func findLogRecord(
	t *testing.T,
	records []testLogRecord,
	message string,
) testLogRecord {
	t.Helper()

	for _, record := range records {
		if record.Message == message {
			return record
		}
	}

	t.Fatalf("log record %q was not found", message)
	return testLogRecord{}
}

func assertAccessLog(
	t *testing.T,
	record testLogRecord,
	requestID string,
	method string,
	path string,
	status int,
) {
	t.Helper()

	if record.Module != "http" {
		t.Fatalf("expected module http, got %q", record.Module)
	}

	if record.RequestID != requestID {
		t.Fatalf("expected request ID %q, got %q", requestID, record.RequestID)
	}

	if record.Method != method {
		t.Fatalf("expected method %q, got %q", method, record.Method)
	}

	if record.Path != path {
		t.Fatalf("expected path %q, got %q", path, record.Path)
	}

	if record.Status != status {
		t.Fatalf("expected status %d, got %d", status, record.Status)
	}

	if record.DurationMS == nil || *record.DurationMS < 0 {
		t.Fatal("expected a non-negative duration_ms")
	}
}
